
const { GoogleGenerativeAI } = require("@google/generative-ai");

let genAI = null;
if (process.env.GEMINI_API_KEY) {
  genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
}
console.log("Gemini API Key Loaded:", !!process.env.GEMINI_API_KEY);

const FALLBACK_PROMPTS = [
  "What was your happiest childhood memory?",
  "Tell about a family tradition that means a lot to you.",
  "Describe a favorite meal or recipe from your childhood.",
  "Who in your family inspired you the most, and why?",
  "Share a funny or unforgettable family moment.",
  "Describe a holiday that you remember fondly.",
  "What small thing made you feel loved as a kid?",
  "Tell a story where your family laughed until they cried.",
  "Which family photo always makes you smile and why?",
  "What was your first job and what did it teach you?"
];

function normalizeText(t = "") {
  return t.trim().replace(/\s+/g, " ").toLowerCase();
}

async function tryGenerateWithModel(modelName, systemPrompt) {
  try {
    const model = genAI.getGenerativeModel({ model: modelName });
    const result = await model.generateContent(systemPrompt);
    const text = (result?.response?.text && String(result.response.text()).trim()) || "";
    if (text && text.length > 6) {
      return { text, model: modelName };
    }
    return null;
  } catch (err) {
   
    console.warn(`Model ${modelName} failed: ${err?.message || err}`);
    return null;
  }
}

module.exports = async function generatePromptText(recentPrompts = []) {
  const seen = new Set((recentPrompts || []).map(normalizeText));
  const pickFallback = () => {
    const candidates = FALLBACK_PROMPTS.filter(p => !seen.has(normalizeText(p)));
    return candidates.length ? candidates[Math.floor(Math.random() * candidates.length)] : FALLBACK_PROMPTS[Math.floor(Math.random() * FALLBACK_PROMPTS.length)];
  };

  // If no API key set, immediate fallback
  if (!genAI) {
    console.warn("No GEMINI_API_KEY found — using local fallback prompt");
    return pickFallback();
  }


  const blockList = [...seen].slice(0, 40).map(t => `- "${t}"`).join("\n");
  const systemInstruction = `
You are a friendly assistant that writes ONE short, warm memory prompt question for a family storytelling app.
Rules:
- Output only the question text (no explanations).
- Keep it under 20 words.
- Avoid the following exact prompts (recently shown): 
${blockList || "- none"}
- Avoid generic filler like "Tell us a story about your family." Prefer something specific and evocative.
`;

  
  const candidates = [
    "gemini-2.5-flash",
    "gemini-2.5-pro",
    "gemini-2.5-flash-001",
    "gemini-2.5-pro-001",
   
    "gemini-2.1",
    "gemini-2.0-flash",
    "text-bison-001" 
  ];

  for (const m of candidates) {
    const attempt = await tryGenerateWithModel(m, systemInstruction);
    if (attempt && attempt.text) {
      console.log(`Prompt generated by model: ${attempt.model}`);
      // ensure it's not a repeat
      const normalized = normalizeText(attempt.text);
      if (!seen.has(normalized)) return attempt.text;
      console.warn("Generated prompt matched recent prompts — falling back to local.");
      break;
    }
  }

  // If none worked -> fallback
  console.warn("All Gemini model attempts failed or returned repeats — using local fallback.");
  return pickFallback();
};
